export const POPULATION = 100
export const FIXED_DT = 1 / 120
export const DEFAULT_SEED = 240519
export const RUN_TIMEOUT = 60
export const BASE_DAMAGE = 35
export const HIT_COOLDOWN = 0.3
export const SHELL_EFFECT = 0.5
export const HIT_FLASH = 0.16

export const RUNNER_WIDTH = 12
export const RUNNER_HEIGHT = 18
export const GRAVITY = 1100
export const LOOK_AHEAD_BASE = 8
export const LOOK_AHEAD_GAIN = 28
export const SPEED_BASE = 100
export const SPEED_GAIN = 200
export const ACCELERATION = 18
export const JUMP_DELAY = .17
export const JUMP_BASE = 310
export const JUMP_GAIN = 220
export const JUMP_COOLDOWN = .22
export const WHEEL_RADIUS = 64
export const WHEEL_ROTATION = 1.5
export const WHEEL_ARMS = 4
export const WHEEL_REACHES = [.72, .86, 1] as const
export const WHEEL_CONTACT_RADIUS_SQUARED = 100
export const TRACK_FORCE = 165
export const PLATFORM_SPEED = 80
